// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: ioam-clt_api.proto

package clt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IOAMService_Report_FullMethodName = "/ioam_api.IOAMService/Report"
)

// IOAMServiceClient is the client API for IOAMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IOAM Service
type IOAMServiceClient interface {
	// Report an IOAM Trace
	Report(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IOAMTrace, emptypb.Empty], error)
}

type iOAMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIOAMServiceClient(cc grpc.ClientConnInterface) IOAMServiceClient {
	return &iOAMServiceClient{cc}
}

func (c *iOAMServiceClient) Report(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IOAMTrace, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IOAMService_ServiceDesc.Streams[0], IOAMService_Report_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IOAMTrace, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IOAMService_ReportClient = grpc.ClientStreamingClient[IOAMTrace, emptypb.Empty]

// IOAMServiceServer is the server API for IOAMService service.
// All implementations must embed UnimplementedIOAMServiceServer
// for forward compatibility.
//
// IOAM Service
type IOAMServiceServer interface {
	// Report an IOAM Trace
	Report(grpc.ClientStreamingServer[IOAMTrace, emptypb.Empty]) error
	mustEmbedUnimplementedIOAMServiceServer()
}

// UnimplementedIOAMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIOAMServiceServer struct{}

func (UnimplementedIOAMServiceServer) Report(grpc.ClientStreamingServer[IOAMTrace, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedIOAMServiceServer) mustEmbedUnimplementedIOAMServiceServer() {}
func (UnimplementedIOAMServiceServer) testEmbeddedByValue()                     {}

// UnsafeIOAMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IOAMServiceServer will
// result in compilation errors.
type UnsafeIOAMServiceServer interface {
	mustEmbedUnimplementedIOAMServiceServer()
}

func RegisterIOAMServiceServer(s grpc.ServiceRegistrar, srv IOAMServiceServer) {
	// If the following call panics, it indicates UnimplementedIOAMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IOAMService_ServiceDesc, srv)
}

func _IOAMService_Report_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IOAMServiceServer).Report(&grpc.GenericServerStream[IOAMTrace, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IOAMService_ReportServer = grpc.ClientStreamingServer[IOAMTrace, emptypb.Empty]

// IOAMService_ServiceDesc is the grpc.ServiceDesc for IOAMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IOAMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ioam_api.IOAMService",
	HandlerType: (*IOAMServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Report",
			Handler:       _IOAMService_Report_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ioam-clt_api.proto",
}
