// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ioam_api.proto

package ioam_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IOAM Trace
type IOAMTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   uint32                 `protobuf:"varint,1,opt,name=NamespaceId,proto3" json:"NamespaceId,omitempty"`
	BitField      uint32                 `protobuf:"fixed32,2,opt,name=BitField,proto3" json:"BitField,omitempty"`
	Nodes         []*IOAMNode            `protobuf:"bytes,3,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOAMTrace) Reset() {
	*x = IOAMTrace{}
	mi := &file_ioam_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOAMTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOAMTrace) ProtoMessage() {}

func (x *IOAMTrace) ProtoReflect() protoreflect.Message {
	mi := &file_ioam_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOAMTrace.ProtoReflect.Descriptor instead.
func (*IOAMTrace) Descriptor() ([]byte, []int) {
	return file_ioam_api_proto_rawDescGZIP(), []int{0}
}

func (x *IOAMTrace) GetNamespaceId() uint32 {
	if x != nil {
		return x.NamespaceId
	}
	return 0
}

func (x *IOAMTrace) GetBitField() uint32 {
	if x != nil {
		return x.BitField
	}
	return 0
}

func (x *IOAMTrace) GetNodes() []*IOAMNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// Opaque State Snapshot
type Opaque struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      uint32                 `protobuf:"varint,1,opt,name=SchemaId,proto3" json:"SchemaId,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"` // variable length field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Opaque) Reset() {
	*x = Opaque{}
	mi := &file_ioam_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Opaque) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opaque) ProtoMessage() {}

func (x *Opaque) ProtoReflect() protoreflect.Message {
	mi := &file_ioam_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opaque.ProtoReflect.Descriptor instead.
func (*Opaque) Descriptor() ([]byte, []int) {
	return file_ioam_api_proto_rawDescGZIP(), []int{1}
}

func (x *Opaque) GetSchemaId() uint32 {
	if x != nil {
		return x.SchemaId
	}
	return 0
}

func (x *Opaque) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// IOAM Node Data
type IOAMNode struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HopLimit          uint32                 `protobuf:"varint,1,opt,name=HopLimit,proto3" json:"HopLimit,omitempty"`
	Id                uint32                 `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	IngressId         uint32                 `protobuf:"varint,3,opt,name=IngressId,proto3" json:"IngressId,omitempty"`
	EgressId          uint32                 `protobuf:"varint,4,opt,name=EgressId,proto3" json:"EgressId,omitempty"`
	TimestampSecs     uint32                 `protobuf:"varint,5,opt,name=TimestampSecs,proto3" json:"TimestampSecs,omitempty"`
	TimestampFrac     uint32                 `protobuf:"varint,6,opt,name=TimestampFrac,proto3" json:"TimestampFrac,omitempty"`
	TransitDelay      uint32                 `protobuf:"varint,7,opt,name=TransitDelay,proto3" json:"TransitDelay,omitempty"`
	QueueDepth        uint32                 `protobuf:"varint,8,opt,name=QueueDepth,proto3" json:"QueueDepth,omitempty"`
	CsumComp          uint32                 `protobuf:"varint,9,opt,name=CsumComp,proto3" json:"CsumComp,omitempty"`
	BufferOccupancy   uint32                 `protobuf:"varint,10,opt,name=BufferOccupancy,proto3" json:"BufferOccupancy,omitempty"`
	IngressIdWide     uint32                 `protobuf:"varint,11,opt,name=IngressIdWide,proto3" json:"IngressIdWide,omitempty"`
	EgressIdWide      uint32                 `protobuf:"varint,12,opt,name=EgressIdWide,proto3" json:"EgressIdWide,omitempty"`
	IdWide            uint64                 `protobuf:"varint,13,opt,name=IdWide,proto3" json:"IdWide,omitempty"`
	NamespaceData     []byte                 `protobuf:"bytes,14,opt,name=NamespaceData,proto3" json:"NamespaceData,omitempty"`         // 4-octet field
	NamespaceDataWide []byte                 `protobuf:"bytes,15,opt,name=NamespaceDataWide,proto3" json:"NamespaceDataWide,omitempty"` // 8-octet field
	OSS               *Opaque                `protobuf:"bytes,16,opt,name=OSS,proto3" json:"OSS,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IOAMNode) Reset() {
	*x = IOAMNode{}
	mi := &file_ioam_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOAMNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOAMNode) ProtoMessage() {}

func (x *IOAMNode) ProtoReflect() protoreflect.Message {
	mi := &file_ioam_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOAMNode.ProtoReflect.Descriptor instead.
func (*IOAMNode) Descriptor() ([]byte, []int) {
	return file_ioam_api_proto_rawDescGZIP(), []int{2}
}

func (x *IOAMNode) GetHopLimit() uint32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

func (x *IOAMNode) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IOAMNode) GetIngressId() uint32 {
	if x != nil {
		return x.IngressId
	}
	return 0
}

func (x *IOAMNode) GetEgressId() uint32 {
	if x != nil {
		return x.EgressId
	}
	return 0
}

func (x *IOAMNode) GetTimestampSecs() uint32 {
	if x != nil {
		return x.TimestampSecs
	}
	return 0
}

func (x *IOAMNode) GetTimestampFrac() uint32 {
	if x != nil {
		return x.TimestampFrac
	}
	return 0
}

func (x *IOAMNode) GetTransitDelay() uint32 {
	if x != nil {
		return x.TransitDelay
	}
	return 0
}

func (x *IOAMNode) GetQueueDepth() uint32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *IOAMNode) GetCsumComp() uint32 {
	if x != nil {
		return x.CsumComp
	}
	return 0
}

func (x *IOAMNode) GetBufferOccupancy() uint32 {
	if x != nil {
		return x.BufferOccupancy
	}
	return 0
}

func (x *IOAMNode) GetIngressIdWide() uint32 {
	if x != nil {
		return x.IngressIdWide
	}
	return 0
}

func (x *IOAMNode) GetEgressIdWide() uint32 {
	if x != nil {
		return x.EgressIdWide
	}
	return 0
}

func (x *IOAMNode) GetIdWide() uint64 {
	if x != nil {
		return x.IdWide
	}
	return 0
}

func (x *IOAMNode) GetNamespaceData() []byte {
	if x != nil {
		return x.NamespaceData
	}
	return nil
}

func (x *IOAMNode) GetNamespaceDataWide() []byte {
	if x != nil {
		return x.NamespaceDataWide
	}
	return nil
}

func (x *IOAMNode) GetOSS() *Opaque {
	if x != nil {
		return x.OSS
	}
	return nil
}

var File_ioam_api_proto protoreflect.FileDescriptor

const file_ioam_api_proto_rawDesc = "" +
	"\n" +
	"\x0eioam_api.proto\x12\bioam_api\x1a\x1bgoogle/protobuf/empty.proto\"s\n" +
	"\tIOAMTrace\x12 \n" +
	"\vNamespaceId\x18\x01 \x01(\rR\vNamespaceId\x12\x1a\n" +
	"\bBitField\x18\x02 \x01(\aR\bBitField\x12(\n" +
	"\x05Nodes\x18\x03 \x03(\v2\x12.ioam_api.IOAMNodeR\x05Nodes\"8\n" +
	"\x06Opaque\x12\x1a\n" +
	"\bSchemaId\x18\x01 \x01(\rR\bSchemaId\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\"\xa0\x04\n" +
	"\bIOAMNode\x12\x1a\n" +
	"\bHopLimit\x18\x01 \x01(\rR\bHopLimit\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\rR\x02Id\x12\x1c\n" +
	"\tIngressId\x18\x03 \x01(\rR\tIngressId\x12\x1a\n" +
	"\bEgressId\x18\x04 \x01(\rR\bEgressId\x12$\n" +
	"\rTimestampSecs\x18\x05 \x01(\rR\rTimestampSecs\x12$\n" +
	"\rTimestampFrac\x18\x06 \x01(\rR\rTimestampFrac\x12\"\n" +
	"\fTransitDelay\x18\a \x01(\rR\fTransitDelay\x12\x1e\n" +
	"\n" +
	"QueueDepth\x18\b \x01(\rR\n" +
	"QueueDepth\x12\x1a\n" +
	"\bCsumComp\x18\t \x01(\rR\bCsumComp\x12(\n" +
	"\x0fBufferOccupancy\x18\n" +
	" \x01(\rR\x0fBufferOccupancy\x12$\n" +
	"\rIngressIdWide\x18\v \x01(\rR\rIngressIdWide\x12\"\n" +
	"\fEgressIdWide\x18\f \x01(\rR\fEgressIdWide\x12\x16\n" +
	"\x06IdWide\x18\r \x01(\x04R\x06IdWide\x12$\n" +
	"\rNamespaceData\x18\x0e \x01(\fR\rNamespaceData\x12,\n" +
	"\x11NamespaceDataWide\x18\x0f \x01(\fR\x11NamespaceDataWide\x12\"\n" +
	"\x03OSS\x18\x10 \x01(\v2\x10.ioam_api.OpaqueR\x03OSS2H\n" +
	"\vIOAMService\x129\n" +
	"\x06Report\x12\x13.ioam_api.IOAMTrace\x1a\x16.google.protobuf.Empty\"\x00(\x01B,Z*github.com/Advanced-Observability/ioam-apib\x06proto3"

var (
	file_ioam_api_proto_rawDescOnce sync.Once
	file_ioam_api_proto_rawDescData []byte
)

func file_ioam_api_proto_rawDescGZIP() []byte {
	file_ioam_api_proto_rawDescOnce.Do(func() {
		file_ioam_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ioam_api_proto_rawDesc), len(file_ioam_api_proto_rawDesc)))
	})
	return file_ioam_api_proto_rawDescData
}

var file_ioam_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ioam_api_proto_goTypes = []any{
	(*IOAMTrace)(nil),     // 0: ioam_api.IOAMTrace
	(*Opaque)(nil),        // 1: ioam_api.Opaque
	(*IOAMNode)(nil),      // 2: ioam_api.IOAMNode
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_ioam_api_proto_depIdxs = []int32{
	2, // 0: ioam_api.IOAMTrace.Nodes:type_name -> ioam_api.IOAMNode
	1, // 1: ioam_api.IOAMNode.OSS:type_name -> ioam_api.Opaque
	0, // 2: ioam_api.IOAMService.Report:input_type -> ioam_api.IOAMTrace
	3, // 3: ioam_api.IOAMService.Report:output_type -> google.protobuf.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ioam_api_proto_init() }
func file_ioam_api_proto_init() {
	if File_ioam_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ioam_api_proto_rawDesc), len(file_ioam_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ioam_api_proto_goTypes,
		DependencyIndexes: file_ioam_api_proto_depIdxs,
		MessageInfos:      file_ioam_api_proto_msgTypes,
	}.Build()
	File_ioam_api_proto = out.File
	file_ioam_api_proto_goTypes = nil
	file_ioam_api_proto_depIdxs = nil
}
